### ISSUE TITLE
Enable DNSSEC for nlx.io

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/nlx#39] opened 2018-01-22 21:31 UTC
Since transfer to nameservers of CloudVPS we lost DNSSEC. This is not optional, so we need to fix it.

**Comment by bartjkdp** [comment] 2018-01-23 09:30
I asked CloudVPS, but I am not sure they offer DNSSEC for .io domains...

**Comment by ehotting** [comment] 2018-01-23 10:35
I'm afraid there is no support for DNSSEC on their nameservers at all. Should not be dependent on TLD anyway, if the root supports it - which is the case for .io .
Which means we need to move nameservers again. Let's postpone that for now.

**Comment by ehotting** [comment] 2018-01-23 11:01
We don't have a legal entity that can do this right now. Perhaps your foundation?

**Comment by bartjkdp** [comment] 2018-01-23 12:55
We have no problems holding the domain for a while. Just let me know, so we can initiate the transfer.

**Comment by bartjkdp** [comment] 2018-01-24 20:37
Duplicate of #40

**Closed by bartjkdp** 2018-01-24 20:37 UTC
Labels: development infra
